### ISSUE TITLE
Jamstack website points to a different URL

### ISSUE THREAD

**Issue by OsakaStarbux** [mrvautin/squido-blog-example#1]
Hi 

Links that should point to this repo on the Jamstack website ( includes Deploy on Netlify button) are broken. The error:

Not found: https://github.com/mrvautin/squido-blog
This repository may not exist or is set to private.

“-example “ is missing from the end.  Also, at docs.squido.org the link to the blog demo is actually the docs site. Like so:

Blog style: https://docs.squido.org

**Comment by mrvautin** [comment]
You are totally right @OsakaStarbux. I've fixed. Thanks.
